apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-sre-assistant
  namespace: ai-sre

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ai-sre-assistant

  template:
    metadata:
      labels:
        app: ai-sre-assistant

    spec:
      serviceAccountName: sre-assistant

      containers:
      - name: assistant
        image: ai-sre-assistant:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-creds
              key: AWS_SESSION_TOKEN
